[package]
name = "security_research_poc"
version = "0.1.0"
edition = "2021"
description = "Modular academic lab for studying Windows API interactions and EDR-friendly telemetry."

[dependencies]
aes = "0.8"
sysinfo = "0.30"
obfstr = "0.4"
image = "0.24"
cipher = "0.4"
cbc = "0.1"             # Modo de operación para AES
block-padding = "0.3"   # Para manejar el relleno (padding) de los datos
sha2 = "0.10"           # Para derivar la clave (Hashing)
hex = "0.4"             # Útil para debuguear y ver la clave generada
windows = { version = "0.54", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_Debug",
] }
